<?php

class OverridingTest {

    public static function test() {
        echo DateTest::test();
    }


}

class Car {
    public final function engineOn() {
        echo '엔진 on';
    }
}

class Porche extends Car {
    public function testMethod()
    {
        parent::engineOn(); // TODO: Change the autogenerated stub
    }
}

$car = new Porche();
$car->engineOn();
$car->testMethod();